[package]
name = "tonic_example_broken_project"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
prost = '0.13.1'
tonic = '0.12.0'

[build-dependencies]
prost-build = '0.13.1'
tonic-build = '0.12.0'

